<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'DFR\\CSS_Vars' => $baseDir . '/src/CSS_Vars.php',
    'DFR\\Init' => $baseDir . '/src/Init.php',
);
